name: ecom_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-272.0.dev <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.5.6
  get_it: ^7.7.0
  injectable: ^2.4.2  
  analyzer: ^6.7.0
  dart_style: ^2.3.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/onboarding_1.jpg
    - assets/images/onboarding_2.jpg
    - assets/images/onboarding_3.jpg
    - assets/images/signup_facebook.png
    - assets/images/signup_google.png
    - assets/images/close_eye_icon.png
    - assets/images/open_eye_icon.png
    - assets/images/pass_icon.png
    - assets/images/person_icon.png
    - assets/images/email_icon.png
    - assets/gifs/email_sent.gif
    - assets/gifs/reg_succesfull.gif
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
