name: ecom_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-272.0.dev <4.0.0'

dependencies:
  analyzer: ^6.7.0
  cupertino_icons: ^1.0.8
  dart_style: ^2.3.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  injectable: ^2.4.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.5.6

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/onboarding_1.jpg
    - assets/images/onboarding_2.jpg
    - assets/images/onboarding_3.jpg
    - assets/images/signup_facebook.png
    - assets/images/signup_google.png
    - assets/images/close_eye_icon.png
    - assets/images/open_eye_icon.png
    - assets/images/pass_icon.png
    - assets/images/person_icon.png
    - assets/images/bell-notification.png
    - assets/images/bell.png
    - assets/images/heart.png
    - assets/images/house-blank.png
    - assets/images/search.png
    - assets/images/delivery.png
    - assets/images/profile.png
    - assets/images/email_icon.png
    - assets/images/profile_active.png
    - assets/images/delivery_active.png
    - assets/images/house-blank_active.png
    - assets/images/heart_active.png
    - assets/images/heart_icon.png
    - assets/images/heart_like_icon.png
    - assets/images/left-chevron.png
    - assets/images/first.png
    - assets/images/second.png
    - assets/images/meme.png
    - assets/gifs/email_sent.gif
    - assets/gifs/reg_succesfull.gif
    - assets/icons/star_icon.png
    - assets/icons/bag_icon.png
    - assets/icons/minus_icon.png
    - assets/icons/plus_icon.png
    - assets/images/filter.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
